elasticsearch:
  image: elasticsearch
  volumes:
    - ./elasticsearch/config:/usr/share/elasticsearch/config
    - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
  ports:
    - 9200:9200
    - 9300:9300
  command: ["elasticsearch", "--security.manager.enabled", "false"]