logstash:
  image: logstash:2.2
  volumes:
    - .:/data/logstash
  command: logstash -f /data/logstash/config/* --debug
  external_links:
    - behavioraistorage_elasticsearch_1:storage.behavior-ai.com

