logstash:
  image: logstash:2.2
  volumes:
    - .:/data/logstash
    - ./logs:/data/logs
  command: logstash -f /data/logstash/config/* --debug
  external_links:
    - behavioraistorage_elasticsearch_1:storage.behavior-ai.com
  log_driver: none
  ports:
    - 8080:8080