application:
  image: busybox
  volumes:
    - .:/usr/share/nginx/html

nginx:
  image: nginx
  volumes_from:
    - application
  expose:
    - 80
  ports:
    - 8001:80
  environment:
    VIRTUAL_HOST: frontapp.behaviorai.docker
    VIRTUAL_PORT: 8001

bower:
  image: digitallyseamless/nodejs-bower-grunt
  volumes_from:
    - application
  working_dir: /data/application
  command: bower install elasticsearch